# Generated by Django 5.0.6 on 2024-07-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
